name: peer_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  get: ^4.6.5

  flutter_nearby_connections: ^1.1.1
  cryptography: ^2.0.5
  collection: ^1.16.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  uuid: ^3.0.7
  flutter_chat_ui: ^1.6.6
  # FORM
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  # DB
  flutter_secure_storage: ^7.0.1
  sembast: ^3.3.1
  path_provider: ^2.0.11
  path: ^1.8.2
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: 2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli:
  separator: "."


